# General settings
# E. Weiand - 01/2022

units           real

atom_style      full
bond_style      harmonic
angle_style     cosine/squared
dihedral_style  none
improper_style  none

# simple LJ sufficient here for fully-functionalized uncharged monolayers
pair_style      lj/gromacs 9 12		# inner outer (LJ)

# turn off LJ/Coulombic interactions between bonded neighbors but not for 1-3 (LJ), 1-4 neighbors (LJ/Coul)
special_bonds   lj 0 1 1 coul 0 0 1

# relative dielectric constant 
# (polarizable water model, not relevant here)
dielectric      2.5

# neighbor list updates
neigh_modify    every 5 	# change to "every 1 delay 0 check yes" 
				# for initial convergence problems

# non-periodic box in z
boundary   	p p f

# runtime variables
variable        Nrun   		equal 2000000	# total runtime, 10 ns, increase if necessary
variable        Ndump  		equal 10000	# dump frequency
variable        Nrestart  	equal 50000	# restart frequency
variable        ts     		equal 5.0	# timestep size (possible to increase in absence of water)
